# Generated by Django 2.2.7 on 2019-11-22 12:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0002_comment_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='ovation',
            field=models.ManyToManyField(blank=True, related_name='ovation', to=settings.AUTH_USER_MODEL),
        ),
    ]
